indaba-backend:
  image: "amidatech/greyscale-backend:$INDABA_ENV"
  environment:
    INDABA_PG_DB: ${INDABA_PG_DB}
    AUTH_SALT: nMsDo)_1fh
    RDS_TESTUSER: ${RDS_TESTUSER}
  ports:
  - "3005:3005"
  links:
  - "memcached"

memcached:
  image: "memcached:latest"
  expose:
  - "11211"

indaba-frontend:
  image: "amidatech/greyscale-client:${INDABA_ENV}"
  links:
  - "indaba-backend"
  environment:
    INDABA_URL: http://indaba-backend:3005
  ports:
  - "80:80"
